// Generated by //js/private/node-patches:compile
"use strict";
/**
 * @license
 * Copyright 2019 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
var __asyncValues = (this && this.__asyncValues) || function (o) {
    if (!Symbol.asyncIterator) throw new TypeError("Symbol.asyncIterator is not defined.");
    var m = o[Symbol.asyncIterator], i;
    return m ? m.call(o) : (o = typeof __values === "function" ? __values(o) : o[Symbol.iterator](), i = {}, verb("next"), verb("throw"), verb("return"), i[Symbol.asyncIterator] = function () { return this; }, i);
    function verb(n) { i[n] = o[n] && function (v) { return new Promise(function (resolve, reject) { v = o[n](v), settle(resolve, reject, v.done, v.value); }); }; }
    function settle(resolve, reject, d, v) { Promise.resolve(v).then(function(v) { resolve({ value: v, done: d }); }, reject); }
};
var __await = (this && this.__await) || function (v) { return this instanceof __await ? (this.v = v, this) : new __await(v); }
var __asyncGenerator = (this && this.__asyncGenerator) || function (thisArg, _arguments, generator) {
    if (!Symbol.asyncIterator) throw new TypeError("Symbol.asyncIterator is not defined.");
    var g = generator.apply(thisArg, _arguments || []), i, q = [];
    return i = {}, verb("next"), verb("throw"), verb("return"), i[Symbol.asyncIterator] = function () { return this; }, i;
    function verb(n) { if (g[n]) i[n] = function (v) { return new Promise(function (a, b) { q.push([n, v, a, b]) > 1 || resume(n, v); }); }; }
    function resume(n, v) { try { step(g[n](v)); } catch (e) { settle(q[0][3], e); } }
    function step(r) { r.value instanceof __await ? Promise.resolve(r.value.v).then(fulfill, reject) : settle(q[0][2], r); }
    function fulfill(value) { resume("next", value); }
    function reject(value) { resume("throw", value); }
    function settle(f, v) { if (f(v), q.shift(), q.length) resume(q[0][0], q[0][1]); }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.escapeFunction = exports.isSubPath = exports.patcher = void 0;
const path = require("path");
const util = require("util");
// using require here on purpose so we can override methods with any
// also even though imports are mutable in typescript the cognitive dissonance is too high because
// es modules
const _fs = require('node:fs');
const url = require('node:url');
const HOP_NON_LINK = Symbol.for('HOP NON LINK');
const HOP_NOT_FOUND = Symbol.for('HOP NOT FOUND');
function patcher(fs = _fs, roots, useLstatPatch) {
    fs = fs || _fs;
    // Make the original version of the library available for when access to the
    // unguarded file system is necessary, such as the esbuild plugin that
    // protects against sandbox escaping that occurs through module resolution
    // in the Go binary. See
    // https://github.com/aspect-build/rules_esbuild/issues/58.
    fs._unpatched = Object.assign({}, fs);
    roots = roots || [];
    roots = roots.filter((root) => fs.existsSync(root));
    if (!roots.length) {
        if (process.env.VERBOSE_LOGS) {
            console.error('fs patcher called without any valid root paths ' + __filename);
        }
        return;
    }
    const origLstat = fs.lstat.bind(fs);
    const origLstatSync = fs.lstatSync.bind(fs);
    const origReaddir = fs.readdir.bind(fs);
    const origReaddirSync = fs.readdirSync.bind(fs);
    const origReadlink = fs.readlink.bind(fs);
    const origReadlinkSync = fs.readlinkSync.bind(fs);
    const origRealpath = fs.realpath.bind(fs);
    const origRealpathNative = fs.realpath
        .native;
    const origRealpathSync = fs.realpathSync.bind(fs);
    const origRealpathSyncNative = fs.realpathSync
        .native;
    const { isInBazelRoot, isEscape } = escapeFunction(roots);
    // =========================================================================
    // fs.lstat
    // =========================================================================
    fs.lstat = function lstat(...args) {
        // preserve error when calling function without required callback
        if (typeof args[args.length - 1] !== 'function') {
            return origLstat(...args);
        }
        const cb = once(args[args.length - 1]);
        // override the callback
        args[args.length - 1] = function lstatCb(err, stats) {
            if (err)
                return cb(err);
            if (!stats.isSymbolicLink()) {
                // the file is not a symbolic link so there is nothing more to do
                return cb(null, stats);
            }
            args[0] = resolvePathLike(args[0]);
            if (!isInBazelRoot(args[0])) {
                // The requested path isn't within a bazel root to begin with so there's
                // no "escaping" to fix.
                return cb(null, stats);
            }
            return guardedReadLink(args[0], guardedReadLinkCb);
            function guardedReadLinkCb(str) {
                if (str != args[0]) {
                    // there are one or more hops within the guards so there is nothing more to do
                    return cb(null, stats);
                }
                // there are no hops so lets report the stats of the real file;
                // we can't use origRealPath here since that function calls lstat internally
                // which can result in an infinite loop
                return unguardedRealPath(args[0], unguardedRealPathCb);
                function unguardedRealPathCb(err, str) {
                    if (err) {
                        if (err.code === 'ENOENT') {
                            // broken link so there is nothing more to do
                            return cb(null, stats);
                        }
                        return cb(err);
                    }
                    return origLstat(str, cb);
                }
            }
        };
        origLstat(...args);
    };
    fs.lstatSync = function lstatSync(...args) {
        const stats = origLstatSync(...args);
        if (!(stats === null || stats === void 0 ? void 0 : stats.isSymbolicLink())) {
            // the file is not a symbolic link so there is nothing more to do
            return stats;
        }
        args[0] = resolvePathLike(args[0]);
        if (!isInBazelRoot(args[0])) {
            // The requested path isn't within a bazel root to begin with so there's
            // no "escaping" to fix.
            return stats;
        }
        const guardedReadLink = guardedReadLinkSync(args[0]);
        if (guardedReadLink != args[0]) {
            // there are one or more hops within the guards so there is nothing more to do
            return stats;
        }
        try {
            args[0] = unguardedRealPathSync(args[0]);
            // there are no hops so lets report the stats of the real file;
            // we can't use origRealPathSync here since that function calls lstat internally
            // which can result in an infinite loop
            return origLstatSync(...args);
        }
        catch (err) {
            if (err.code === 'ENOENT') {
                // broken link so there is nothing more to do
                return stats;
            }
            throw err;
        }
    };
    // =========================================================================
    // fs.realpath
    // =========================================================================
    fs.realpath = function realpath(...args) {
        // preserve error when calling function without required callback
        if (typeof args[args.length - 1] !== 'function') {
            return origRealpath(...args);
        }
        const cb = once(args[args.length - 1]);
        args[args.length - 1] = function realpathCb(err, str) {
            if (err)
                return cb(err);
            const escapedRoot = isEscape(args[0], str);
            if (escapedRoot) {
                return guardedRealPath(args[0], cb, escapedRoot);
            }
            else {
                return cb(null, str);
            }
        };
        origRealpath(...args);
    };
    fs.realpath.native = function realpath_native(...args) {
        // preserve error when calling function without required callback
        if (typeof args[args.length - 1] !== 'function') {
            return origRealpathNative(...args);
        }
        const cb = once(args[args.length - 1]);
        args[args.length - 1] = function nativeCb(err, str) {
            if (err)
                return cb(err);
            const escapedRoot = isEscape(args[0], str);
            if (escapedRoot) {
                return guardedRealPath(args[0], cb, escapedRoot);
            }
            else {
                return cb(null, str);
            }
        };
        origRealpathNative(...args);
    };
    fs.realpathSync = function realpathSync(...args) {
        const str = origRealpathSync(...args);
        const escapedRoot = isEscape(args[0], str);
        if (escapedRoot) {
            return guardedRealPathSync(args[0], escapedRoot);
        }
        return str;
    };
    fs.realpathSync.native = function native_realpathSync(...args) {
        const str = origRealpathSyncNative(...args);
        const escapedRoot = isEscape(args[0], str);
        if (escapedRoot) {
            return guardedRealPathSync(args[0], escapedRoot);
        }
        return str;
    };
    // =========================================================================
    // fs.readlink
    // =========================================================================
    fs.readlink = function readlink(...args) {
        // preserve error when calling function without required callback
        if (typeof args[args.length - 1] !== 'function') {
            return origReadlink(...args);
        }
        const cb = once(args[args.length - 1]);
        args[args.length - 1] = function readlinkCb(err, str) {
            if (err)
                return cb(err);
            const resolved = resolvePathLike(args[0]);
            str = path.resolve(path.dirname(resolved), str);
            const escapedRoot = isEscape(resolved, str);
            if (escapedRoot) {
                return nextHop(str, readlinkNextHopCb);
                function readlinkNextHopCb(next) {
                    if (!next) {
                        if (next == undefined) {
                            // The escape from the root is not mappable back into the root; throw EINVAL
                            return cb(enoent('readlink', args[0]));
                        }
                        else {
                            // The escape from the root is not mappable back into the root; throw EINVAL
                            return cb(einval('readlink', args[0]));
                        }
                    }
                    next = path.resolve(path.dirname(resolved), path.relative(path.dirname(str), next));
                    if (next != resolved &&
                        !isEscape(resolved, next, [escapedRoot])) {
                        return cb(null, next);
                    }
                    // The escape from the root is not mappable back into the root; we must make
                    // this look like a real file so we call readlink on the realpath which we
                    // expect to return an error
                    return origRealpath(resolved, readlinkRealpathCb);
                    function readlinkRealpathCb(err, str) {
                        if (err)
                            return cb(err);
                        return origReadlink(str, cb);
                    }
                }
            }
            else {
                return cb(null, str);
            }
        };
        origReadlink(...args);
    };
    fs.readlinkSync = function readlinkSync(...args) {
        const resolved = resolvePathLike(args[0]);
        const str = path.resolve(path.dirname(resolved), origReadlinkSync(...args));
        const escapedRoot = isEscape(resolved, str);
        if (escapedRoot) {
            // The symlink escapes the root, but maybe if we resolve other
            // symlinks in the path we can get back into the root, so let's
            // try to take another hop preferring one that keeps us in the
            // sandbox. (NOTE(tenzin): I'm not sure why this would ever be the case).
            let next = nextHopSync(str);
            if (!next) {
                // The escape from the root is not mappable back into the root
                // NOTE(tenzin): I think technically both of these branches
                // should be unreachable, since if we were able to resolve the
                // symlink with `origReadlinkSync`, it should both be a defined
                // file and have symlink path elements. This code seems strange.
                if (next == undefined) {
                    // `str` isn't even a valid path to a file; throw ENOENT
                    throw enoent('readlink', args[0]);
                }
                else {
                    // `str` is not a symlink; throw EINVAL
                    throw einval('readlink', args[0]);
                }
            }
            next = path.resolve(path.dirname(resolved), path.relative(path.dirname(str), next));
            if (next != resolved && !isEscape(resolved, next, [escapedRoot])) {
                return next;
            }
            // The escape from the root is not mappable back into the root; throw EINVAL
            // In the case of the file existing, this is equivalent to telling the caller
            // the file is not a symbolic link (this is how we keep things contained to the roots).
            throw einval('readlink', args[0]);
        }
        return str;
    };
    // =========================================================================
    // fs.readdir
    // =========================================================================
    fs.readdir = function readdir(...args) {
        // preserve error when calling function without required callback
        if (typeof args[args.length - 1] !== 'function') {
            return origReaddir(...args);
        }
        const cb = once(args[args.length - 1]);
        const p = resolvePathLike(args[0]);
        args[args.length - 1] = function readdirCb(err, result) {
            if (err)
                return cb(err);
            // user requested withFileTypes
            if (result[0] && result[0].isSymbolicLink) {
                Promise.all(result.map((v) => handleDirent(p, v)))
                    .then(() => {
                    cb(null, result);
                })
                    .catch((err) => {
                    cb(err);
                });
            }
            else {
                // string array return for readdir.
                cb(null, result);
            }
        };
        origReaddir(...args);
    };
    fs.readdirSync = function readdirSync(...args) {
        const res = origReaddirSync(...args);
        const p = resolvePathLike(args[0]);
        res.forEach((v) => {
            handleDirentSync(p, v);
        });
        return res;
    };
    // =========================================================================
    // fs.opendir
    // =========================================================================
    if (fs.opendir) {
        const origOpendir = fs.opendir.bind(fs);
        fs.opendir = function opendir(...args) {
            // if this is not a function opendir should throw an error.
            // we call it so we don't have to throw a mock
            if (typeof args[args.length - 1] === 'function') {
                const cb = once(args[args.length - 1]);
                args[args.length - 1] = async function opendirCb(err, dir) {
                    try {
                        cb(null, await handleDir(dir));
                    }
                    catch (err) {
                        cb(err);
                    }
                };
                origOpendir(...args);
            }
            else {
                return origOpendir(...args).then((dir) => {
                    return handleDir(dir);
                });
            }
        };
    }
    // =========================================================================
    // fs.promises
    // =========================================================================
    /**
     * patch fs.promises here.
     *
     * this requires a light touch because if we trigger the getter on older nodejs versions
     * it will log an experimental warning to stderr
     *
     * `(node:62945) ExperimentalWarning: The fs.promises API is experimental`
     *
     * this api is available as experimental without a flag so users can access it at any time.
     */
    const promisePropertyDescriptor = Object.getOwnPropertyDescriptor(fs, 'promises');
    if (promisePropertyDescriptor) {
        const promises = {};
        promises.lstat = util.promisify(fs.lstat);
        // NOTE: node core uses the newer realpath function fs.promises.native instead of fs.realPath
        promises.realpath = util.promisify(fs.realpath.native);
        promises.readlink = util.promisify(fs.readlink);
        promises.readdir = util.promisify(fs.readdir);
        if (fs.opendir)
            promises.opendir = util.promisify(fs.opendir);
        // handle experimental api warnings.
        // only applies to version of node where promises is a getter property.
        if (promisePropertyDescriptor.get) {
            const oldGetter = promisePropertyDescriptor.get.bind(fs);
            const cachedPromises = {};
            promisePropertyDescriptor.get = () => {
                const _promises = oldGetter();
                Object.assign(cachedPromises, _promises, promises);
                return cachedPromises;
            };
            Object.defineProperty(fs, 'promises', promisePropertyDescriptor);
        }
        else {
            // api can be patched directly
            Object.assign(fs.promises, promises);
        }
    }
    // =========================================================================
    // helper functions for dirs
    // =========================================================================
    async function handleDir(dir) {
        const p = path.resolve(dir.path);
        const origIterator = dir[Symbol.asyncIterator].bind(dir);
        const origRead = dir.read.bind(dir);
        dir[Symbol.asyncIterator] = function () {
            return __asyncGenerator(this, arguments, function* () {
                var _a, e_1, _b, _c;
                try {
                    for (var _d = true, _f = __asyncValues(origIterator()), _g; _g = yield __await(_f.next()), _a = _g.done, !_a;) {
                        _c = _g.value;
                        _d = false;
                        try {
                            const entry = _c;
                            yield __await(handleDirent(p, entry));
                            yield yield __await(entry);
                        }
                        finally {
                            _d = true;
                        }
                    }
                }
                catch (e_1_1) { e_1 = { error: e_1_1 }; }
                finally {
                    try {
                        if (!_d && !_a && (_b = _f.return)) yield __await(_b.call(_f));
                    }
                    finally { if (e_1) throw e_1.error; }
                }
            });
        };
        dir.read = async function handleDirRead(...args) {
            if (typeof args[args.length - 1] === 'function') {
                const cb = args[args.length - 1];
                args[args.length - 1] = async function handleDirReadCb(err, entry) {
                    cb(err, entry ? await handleDirent(p, entry) : null);
                };
                origRead(...args);
            }
            else {
                const entry = await origRead(...args);
                if (entry) {
                    await handleDirent(p, entry);
                }
                return entry;
            }
        };
        const origReadSync = dir.readSync.bind(dir);
        dir.readSync = function handleDirReadSync() {
            return handleDirentSync(p, origReadSync()); // intentionally sync for simplicity
        };
        return dir;
    }
    function handleDirent(p, v) {
        return new Promise(function handleDirentExecutor(resolve, reject) {
            if (!v.isSymbolicLink()) {
                return resolve(v);
            }
            const f = path.resolve(p, v.name);
            return guardedReadLink(f, handleDirentReadLinkCb);
            function handleDirentReadLinkCb(str) {
                if (f != str) {
                    return resolve(v);
                }
                // There are no hops so we should hide the fact that the file is a symlink
                v.isSymbolicLink = () => false;
                origRealpath(f, function handleDirentRealpathCb(err, str) {
                    if (err) {
                        throw err;
                    }
                    fs.stat(str, function handleDirentStatCb(err, stat) {
                        if (err) {
                            throw err;
                        }
                        patchDirent(v, stat);
                        resolve(v);
                    });
                });
            }
        });
    }
    function handleDirentSync(p, v) {
        if (v && v.isSymbolicLink) {
            if (v.isSymbolicLink()) {
                const f = path.resolve(p, v.name);
                if (f == guardedReadLinkSync(f)) {
                    // There are no hops so we should hide the fact that the file is a symlink
                    v.isSymbolicLink = () => false;
                    const stat = fs.statSync(origRealpathSync(f));
                    patchDirent(v, stat);
                }
            }
        }
    }
    function nextHop(loc, cb) {
        let nested = '';
        let maybe = loc;
        let escapedHop = false;
        readHopLink(maybe, function readNextHop(link) {
            if (link === HOP_NOT_FOUND) {
                return cb(undefined);
            }
            if (link !== HOP_NON_LINK) {
                if (nested) {
                    link = link + path.sep + nested;
                }
                if (!isEscape(loc, link)) {
                    return cb(link);
                }
                if (!escapedHop) {
                    escapedHop = link;
                }
            }
            const dirname = path.dirname(maybe);
            if (!dirname ||
                dirname == maybe ||
                dirname == '.' ||
                dirname == '/') {
                // not a link
                return cb(escapedHop);
            }
            nested = path.basename(maybe) + (nested ? path.sep + nested : '');
            maybe = dirname;
            readHopLink(maybe, readNextHop);
        });
    }
    const hopLinkCache = Object.create(null);
    /**
     * Read the contents of the symlink located at path p.
     *
     * If the file does not exist, returns HOP_NOT_FOUND.
     * If the file is not a symlink, returns HOP_NON_LINK.
     */
    function readHopLinkSync(p) {
        if (hopLinkCache[p]) {
            return hopLinkCache[p];
        }
        let link;
        try {
            if (origLstatSync(p).isSymbolicLink()) {
                link = origReadlinkSync(p);
                if (link) {
                    if (!path.isAbsolute(link)) {
                        link = path.resolve(path.dirname(p), link);
                    }
                }
                else {
                    link = HOP_NON_LINK;
                }
            }
            else {
                link = HOP_NON_LINK;
            }
        }
        catch (err) {
            if (err.code === 'ENOENT') {
                // file does not exist
                link = HOP_NOT_FOUND;
            }
            else {
                link = HOP_NON_LINK;
            }
        }
        hopLinkCache[p] = link;
        return link;
    }
    function readHopLink(p, cb) {
        if (hopLinkCache[p]) {
            return cb(hopLinkCache[p]);
        }
        origReadlink(p, function readHopLinkCb(err, link) {
            if (err) {
                let result;
                if (err.code === 'ENOENT') {
                    // file does not exist
                    result = HOP_NOT_FOUND;
                }
                else {
                    result = HOP_NON_LINK;
                }
                hopLinkCache[p] = result;
                return cb(result);
            }
            if (link === undefined) {
                hopLinkCache[p] = HOP_NON_LINK;
                return cb(HOP_NON_LINK);
            }
            if (!path.isAbsolute(link)) {
                link = path.resolve(path.dirname(p), link);
            }
            hopLinkCache[p] = link;
            cb(link);
        });
    }
    /**
     * Takes one hop in symlink traversal (i.e.: at most one symlink in a path is resolved, and only
     * resolved one step).
     *
     * For each return condition, resolves the "rightmost" symlink e.g. if
     * resolving `/a/b/c`, where `/a/b` -> `../d` and `a/b/c` -> `../f` then in
     * theory you could take two possible hops, either `/a/b/c` -> `/a/d/c` or
     * `/a/b/c` -> `/a/b/f` (both would resolve to the same file). Assuming
     * neither are escapes (or both are), this function returns `/a/b/f` (breaks
     * ties by resolving the rightmost hop).
     *
     * However, note that if it were something like `c` -> `/g`, `/a` is our only root,
     * then we would return `/a/d/c` (as it is not an escape, whereas `/g` is).
     *
     * The way most downstream consumers use this in the context of preventing sandbox escapes
     * is to resolve as many symlink hops as possible that do NOT escape the sandbox, then
     * on the first hop that does, just return the path of the symlink itself.
     *
     * Returns:
     * - If we can resolve a symlink that does not lead to an escape: returns the new target path.
     * - If the only available symlink(s) lead to an escape: returns the target path of resolving the
     *  rightmost symlink.
     * - If there are no symlinks to resolve: returns false.
     * - If `loc` is not a valid path (no file at that path): returns undefined.
     */
    function nextHopSync(loc) {
        // Loop invariant: maybe + nested = loc
        // i.e.: nested tracks the segments of the path that have been "consumed" as we traverse up the directory tree.
        let nested = '';
        // Path of current file we're evaluating (could be a dir or symlink, "file" in the linux sense).
        // maybe traverses up the directory tree each loop iteration until a termination condition is hit:
        // /a/b/c -> /a/b -> /a -> /
        let maybe = loc;
        // Stores the first target path that escaped the root.
        let escapedHop = false;
        for (;;) {
            let link = readHopLinkSync(maybe);
            if (link === HOP_NOT_FOUND) {
                // maybe points to a non-existent file
                return undefined;
            }
            if (link !== HOP_NON_LINK) {
                // `maybe` is a symlink targeting `link`.
                if (nested) {
                    // Re-add the child path components to the target path.
                    // e.g.: If loc was /a/b/c and /a/b is a symlink targeting /d, then /a/b/c
                    // should resolve to /d/c, so link = /d/c after this line.
                    link = link + path.sep + nested;
                }
                if (!isEscape(loc, link)) {
                    // This symlink is not an escape, return the target path.
                    return link;
                }
                // This symlink is an escape.
                if (!escapedHop) {
                    // This symlink is the first escape we've encountered.
                    // Record the target.
                    escapedHop = link;
                }
            }
            // At this point the following cases:
            // - maybe is not a symlink
            // - maybe is a symlink that escapes the root
            // dirname stores the parent dir of current candidate path.
            const dirname = path.dirname(maybe);
            if (!dirname ||
                // This should catch terminal conditions when maybe is like:
                // "/", ".", or "C:"
                dirname == maybe ||
                dirname == '.' ||
                dirname == '/') {
                // We have traversed up the parent directories, return the
                // first escape we encountered.
                return escapedHop;
            }
            nested = path.basename(maybe) + (nested ? path.sep + nested : '');
            // Go up the directory tree, try parent dir as next potential link.
            maybe = dirname;
            // Loop invariant restored: maybe + nested = loc
        }
    }
    function guardedReadLink(start, cb) {
        let loc = start;
        return nextHop(loc, guardedReadLinkHopCb);
        function guardedReadLinkHopCb(next) {
            if (!next) {
                // we're no longer hopping but we haven't escaped;
                // something funky happened in the filesystem
                return cb(loc);
            }
            if (isEscape(loc, next)) {
                // this hop takes us out of the guard
                return cb(loc);
            }
            return cb(next);
        }
    }
    /**
     * Takes one hop in symlink traversal (preferring hops that don't escape),
     * and returns the target of the symlink if it does not escape the sandbox.
     * Or: returns the symlink path itself if it escapes the sandbox.
     *
     * If the next hop would escape the sandbox, returns `start`.
     * If `start` is not a symlink (nor has any symlink components), returns `start`.
     */
    function guardedReadLinkSync(start) {
        let loc = start;
        let next = nextHopSync(loc);
        if (!next) {
            // we're no longer hopping but we haven't escaped;
            // something funky happened in the filesystem
            // Or we were passed a non-symlink/non-existent file.
            return loc;
        }
        if (isEscape(loc, next)) {
            // this hop takes us out of the guard
            return loc;
        }
        return next;
    }
    function unguardedRealPath(start, cb) {
        start = stringifyPathLike(start); // handle the "undefined" case (matches behavior as fs.realpath)
        function oneHop(loc, cb) {
            nextHop(loc, function oneHopeNextCb(next) {
                if (next == undefined) {
                    // file does not exist (broken link)
                    return cb(enoent('realpath', start));
                }
                else if (!next) {
                    // we've hit a real file
                    return cb(null, loc);
                }
                oneHop(next, cb);
            });
        }
        oneHop(start, cb);
    }
    function guardedRealPath(start, cb, escapedRoot = undefined) {
        start = stringifyPathLike(start); // handle the "undefined" case (matches behavior as fs.realpath)
        function oneHop(loc, cb) {
            nextHop(loc, function guardedRealPathHopCb(next) {
                if (!next) {
                    // we're no longer hopping but we haven't escaped
                    return fs.exists(loc, function guardedRealPathExistsCb(e) {
                        if (e) {
                            // we hit a real file within the guard and can go no further
                            return cb(null, loc);
                        }
                        else {
                            // something funky happened in the filesystem
                            return cb(enoent('realpath', start));
                        }
                    });
                }
                if (escapedRoot
                    ? isEscape(loc, next, [escapedRoot])
                    : isEscape(loc, next)) {
                    // this hop takes us out of the guard
                    return cb(null, loc);
                }
                oneHop(next, cb);
            });
        }
        oneHop(start, cb);
    }
    /**
     * Fully resolves all symlinks in a path, (theoretically equivalent to intrinsic `realpath`).
     */
    function unguardedRealPathSync(start) {
        start = stringifyPathLike(start); // handle the "undefined" case (matches behavior as fs.realpathSync)
        for (let loc = start, next;; loc = next) {
            next = nextHopSync(loc);
            if (next == undefined) {
                // file does not exist (broken link)
                throw enoent('realpath', start);
            }
            else if (!next) {
                // we've hit a real file
                return loc;
            }
        }
    }
    /**
     * "Guarded" realpath implementation.
     *
     * This means it traverses all symlinks that do not lead to an escape, then returns the path.
     */
    function guardedRealPathSync(start, escapedRoot = undefined) {
        start = stringifyPathLike(start); // handle the "undefined" case (matches behavior as fs.realpathSync)
        for (let loc = start, next;; loc = next) {
            next = nextHopSync(loc);
            if (!next) {
                // we're no longer hopping but we haven't escaped
                if (fs.existsSync(loc)) {
                    // we hit a real file within the guard and can go no further
                    return loc;
                }
                else {
                    // something funky happened in the filesystem; throw ENOENT
                    throw enoent('realpath', start);
                }
            }
            if (escapedRoot
                ? isEscape(loc, next, [escapedRoot])
                : isEscape(loc, next)) {
                // this hop takes us out of the guard
                return loc;
            }
        }
    }
    // OUR PATCH SECTION FOR NODE INTERNAL LSTAT BINDING
    // All credit goes to `devversion` on Github for sharing the patch solution:
    // https://github.com/aspect-build/rules_js/issues/362#issuecomment-2950303149
    if (useLstatPatch) {
        // We guard the `require` statements to avoid triggering the warning message
        // when the patch isn't enabled.
        const { internalBinding } = require('internal/test/binding');
        const { getStatsFromBinding } = require('internal/fs/utils');
        const internalFs = internalBinding('fs');
        const _originalLStatFsInternal = internalFs.lstat;
        // Implementation
        function _originalLStatFs(...args) {
            return _originalLStatFsInternal(...args);
        }
        const _originalStatFsInternal = internalFs.stat;
        function _originalStatFs(...args) {
            return _originalStatFsInternal(...args);
        }
        if (internalFs.lstat) {
            // Almost same logic as existing patcher, just that we use `getStatsFromBinding`.
            /**
             * Guard the stats object returned from the internal lstat call (called as a shim layer on the result returned from the internal lstat call).
             */
            const guardInternalStats = (path, bigint, stats, cb) => {
                const statsObj = getStatsFromBinding(stats);
                if (!statsObj.isSymbolicLink()) {
                    // the file is not a symbolic link so there is nothing more to do
                    return cb(null, stats);
                }
                path = resolvePathLike(path);
                if (!isInBazelRoot(path)) {
                    // The file didn't start in a bazel root, so no escaping to fix.
                    return cb(null, stats);
                }
                return guardedReadLink(path, (str) => {
                    if (str != path) {
                        // there are one or more hops within the guards so there is nothing more to do
                        return cb(null, stats);
                    }
                    // there are no hops so lets report the stats of the real file;
                    // we can't use origRealPath here since that function calls lstat internally
                    // which can result in an infinite loop
                    return unguardedRealPath(path, (err, realPath) => {
                        if (err) {
                            if (err.code === 'ENOENT') {
                                // broken link so there is nothing more to do
                                return cb(null, stats);
                            }
                            return cb(err, null);
                        }
                        // Call _originalStatFs on the real path to get the actual file stats
                        // We use stat (not lstat) because we want the stats of the target file.
                        const statReq = new internalFs.FSReqCallback(bigint);
                        statReq.oncomplete = (err, realStats) => {
                            if (err) {
                                if (err.code === 'ENOENT') {
                                    // broken link so there is nothing more to do
                                    return cb(null, stats);
                                }
                                return cb(err, null);
                            }
                            return cb(null, realStats);
                        };
                        return _originalStatFs(realPath, bigint, statReq);
                    });
                });
            };
            /**
             * Guard the stats object returned from the internal lstat call (called as a shim layer on the result returned from the internal lstat call).
             */
            // Almost same logic as existing patcher, just that we use `getStatsFromBinding`.
            const guardInternalStatsSync = (path, bigint, throwIfNoEntry, stats) => {
                // No stats available.
                if (!stats) {
                    return stats;
                }
                const statsObj = getStatsFromBinding(stats);
                if (!statsObj.isSymbolicLink()) {
                    // the file is not a symbolic link so there is nothing more to do
                    return stats;
                }
                path = resolvePathLike(path);
                if (!isInBazelRoot(path)) {
                    // The path isn't within a bazel root so there's technically no "escape" to fix.
                    // e.g.: if program tries to access `/tmp` we don't want to patch that.
                    return stats;
                }
                const guardedReadLink = guardedReadLinkSync(path);
                if (guardedReadLink != path) {
                    // There are one or more hops within the guards so we are safe to let the
                    // caller know it's a symlink (as even if they follow it they'll be within
                    // sandbox).
                    return stats;
                }
                try {
                    // There are no hops so lets report the stats of the real file since
                    // lstat on a normal file should return the what stat would;
                    // We can just call `stat` directly since it resolves symlinks (which is
                    // what we want here).
                    return _originalStatFs(path, bigint, undefined, throwIfNoEntry);
                }
                catch (err) {
                    if (err.code === 'ENOENT') {
                        // broken link so there is nothing more to do
                        return stats;
                    }
                    throw err;
                }
            };
            internalFs.lstat = function (path, bigint, reqCallbackOrUsePromises, throwIfNoEntry) {
                // NOTE(tenzin): This is a very targeted/hacky way to check if
                // we should apply guarding that comes from the original patch.
                // Also the check against whether the stack trace includes eeguardStats
                // seems unnecessary for correctness (in theory our patch should only ever call
                // into the internal fs functions, which should never themselves
                // call eeguardStats. And even if the passed callback references
                // a patched fs function, the stack trace should no longer
                // include the eeguardStats function, because it would've been
                // popped off stack by the time callback is invoked).
                const st = new Error().stack;
                const inFinalizeResolution = st.includes('finalizeResolution (node:internal/modules/esm/resolve');
                const inGuardInternalStats = st.includes('guardInternalStats');
                // For both correctness and speed we only apply guarding logic when
                // we're inside of the ESM resolver's finalizeResolution function (which
                // is the one that calls realpath to escape the sandbox). When we removed
                // the guarding the patch was both slower, and incorrect (e2e demo test
                // would fail). I think this is because without the guard we can end up
                // in cases where patched fs.lstat calls patched internalFs.lstat, which
                // is not the semantics that the patched fs.lstat expects.
                const needsGuarding = inFinalizeResolution && !inGuardInternalStats;
                if (!needsGuarding) {
                    return _originalLStatFs.call(internalFs, path, bigint, reqCallbackOrUsePromises, throwIfNoEntry);
                }
                if (typeof reqCallbackOrUsePromises === 'symbol') {
                    const usePromises = reqCallbackOrUsePromises;
                    return _originalLStatFs
                        .call(internalFs, path, bigint, usePromises, throwIfNoEntry)
                        .then((stats) => {
                        return new Promise((resolve, reject) => {
                            guardInternalStats(path, bigint, stats, (err, guardedStats) => {
                                err
                                    ? reject(err)
                                    : resolve(guardedStats);
                            });
                        });
                    });
                }
                else if (reqCallbackOrUsePromises !== undefined) {
                    const reqCallback = reqCallbackOrUsePromises;
                    // Just re-use the promise path above.
                    internalFs
                        .lstat(path, bigint, internalFs.kUsePromises, throwIfNoEntry)
                        .then((stats) => reqCallback.oncomplete(null, stats))
                        .catch((err) => reqCallback.oncomplete(err, undefined));
                }
                else {
                    const stats = _originalLStatFs.call(internalFs, path, bigint, undefined, throwIfNoEntry);
                    if (!stats) {
                        return stats;
                    }
                    return guardInternalStatsSync(path, bigint, throwIfNoEntry, stats);
                }
            };
        }
    }
}
exports.patcher = patcher;
// =========================================================================
// generic helper functions
// =========================================================================
function isSubPath(parent, child) {
    return (parent === child ||
        (child[parent.length] === path.sep && child.startsWith(parent)));
}
exports.isSubPath = isSubPath;
function stringifyPathLike(p) {
    if (p instanceof URL) {
        return url.fileURLToPath(p);
    }
    else {
        return String(p);
    }
}
function resolvePathLike(p) {
    return path.resolve(stringifyPathLike(p));
}
function normalizePathLike(p) {
    const s = stringifyPathLike(p);
    // TODO: are URLs always absolute?
    if (!path.isAbsolute(s)) {
        return path.resolve(s);
    }
    else {
        return path.normalize(s);
    }
}
function escapeFunction(_roots) {
    // Ensure roots are always absolute.
    // Sort to ensure escaping multiple roots chooses the longest one.
    const defaultRoots = _roots
        .map((root) => path.resolve(root))
        .sort((a, b) => b.length - a.length);
    /**
     * Detects whether a symlink escapes the provided roots (given the symlinks
     * path and its target path).
     *
     * A symlink is considered an escape when the symlink is within a root but the
     * target is not.
     *
     * If it's not an escape, returns false.
     *
     * If it is an escape, returns the first root that the symlink is within (using
     * the defaultRoots this should be the most specific root that matched).
     */
    function fs_isEscape(linkPath, linkTarget, roots = defaultRoots) {
        // linkPath is the path of the symlink file itself
        // linkTarget is a path that the symlink points to one or more hops away
        // linkTarget must already be normalized
        linkPath = normalizePathLike(linkPath);
        for (const root of roots) {
            // If the link is in the root check if the realPath has escaped
            if (isSubPath(root, linkPath) && !isSubPath(root, linkTarget)) {
                return root;
            }
        }
        return false;
    }
    /**
     * Returns true if the path is within one of the provided bazel roots.
     *
     * By default the roots are the execroot (may be sandboxed) and runfiles root
     * (runfiles root should always be subpath of execroot).
     */
    function fs_isInBazelRoot(maybeLinkPath, roots = defaultRoots) {
        // maybeLinkPath is the path which may be a symlink
        // maybeLinkPath must already be normalized
        for (const root of roots) {
            // If the link is in the root check if the realPath has escaped
            if (isSubPath(root, maybeLinkPath)) {
                return true;
            }
        }
        return false;
    }
    return {
        isEscape: fs_isEscape,
        isInBazelRoot: fs_isInBazelRoot,
    };
}
exports.escapeFunction = escapeFunction;
function once(fn) {
    let called = false;
    return function callOnce(...args) {
        if (called)
            return;
        called = true;
        let err = false;
        try {
            fn(...args);
        }
        catch (_e) {
            err = _e;
        }
        // blow the stack to make sure this doesn't fall into any unresolved promise contexts
        if (err) {
            setImmediate(() => {
                throw err;
            });
        }
    };
}
function patchDirent(dirent, stat) {
    // add all stat is methods to Dirent instances with their result.
    for (const i in stat) {
        if (i.startsWith('is') && typeof stat[i] === 'function') {
            //
            const result = stat[i]();
            if (result)
                dirent[i] = () => true;
            else
                dirent[i] = () => false;
        }
    }
}
function enoent(s, p) {
    let err = new Error(`ENOENT: no such file or directory, ${s} '${p}'`);
    err.errno = -2;
    err.syscall = s;
    err.code = 'ENOENT';
    err.path = p;
    return err;
}
function einval(s, p) {
    let err = new Error(`EINVAL: invalid argument, ${s} '${p}'`);
    err.errno = -22;
    err.syscall = s;
    err.code = 'EINVAL';
    err.path = p;
    return err;
}
